# Generated by Django 2.2.28 on 2024-03-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibroLink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
    ]
