# Generated by Django 2.2.28 on 2024-03-19 20:35

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LibroLink', '0003_auto_20240318_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='date_established',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('userA', 'userB')},
        ),
    ]
