# Generated by Django 2.2.28 on 2024-03-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibroLink', '0004_auto_20240319_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
