# Generated by Django 2.2.28 on 2024-03-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibroLink', '0005_remove_userprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userID',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
